CLASSES = {
    0: 'Límite de velocidad (20 km/h)',
    1: 'Límite de velocidad (30 km/h)',
    2: 'Límite de velocidad (50 km/h)',
    3: 'Límite de velocidad (60 km/h)',
    4: 'Límite de velocidad (70 km/h)',
    5: 'Límite de velocidad (80 km/h)',
    6: 'Fin límite de velocidad (80 km/h)',
    7: 'Límite de velocidad (100 km/h)',
    8: 'Límite de velocidad (120 km/h)',
    9: 'Prohibido adelantar',
    10: 'Prohibido adelantar vehículos > 3.5t',
    11: 'Intersección con prioridad',
    12: 'Carretera prioritaria',
    13: 'Ceder el paso',
    14: 'Alto',
    15: 'Prohibido vehículos',
    16: 'Prohibido vehículos > 3.5t',
    17: 'Prohibido el acceso',
    18: 'Peligro general',
    19: 'Curva peligrosa a la izquierda',
    20: 'Curva peligrosa a la derecha',
    21: 'Curva doble',
    22: 'Carretera irregular',
    23: 'Carretera resbaladiza',
    24: 'Carretera se estrecha por la derecha',
    25: 'Obras',
    26: 'Semáforos',
    27: 'Peatones',
    28: 'Cruce de niños',
    29: 'Cruce de bicicletas',
    30: 'Peligro de hielo/nieve',
    31: 'Cruce de animales salvajes',
    32: 'Fin prohibiciones de velocidad y adelantamiento',
    33: 'Gire a la derecha',
    34: 'Gire a la izquierda',
    35: 'Solo adelante',
    36: 'Adelante o derecha',
    37: 'Adelante o izquierda',
    38: 'Mantenga la derecha',
    39: 'Mantenga la izquierda',
    40: 'Rotonda obligatoria',
    41: 'Fin prohibición de adelantar',
    42: 'Fin prohibición de adelantar vehículos > 3.5t'
}

def get_class_name(class_id):
    return CLASSES.get(class_id, f"Clase desconocida ({class_id})")